// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.CardView = (function(_super) {
    __extends(CardView, _super);

    function CardView() {
      _ref = CardView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    CardView.prototype.template = _.template('\
  <li>\
      <a class="card rank-<%= valueCSS %> <%= suitNameCSS %>" href="#">\
          <span class="rank"><%= rankName %></span>\
          <span class="suit"><%= suitNameX %></span>\
      </a>\
  </li>\
  ');

    CardView.prototype.initialize = function() {
      var _this = this;
      this.model.on('change', function() {
        return _this.render;
      });
      return this.render();
    };

    CardView.prototype.render = function() {
      this.$el.children().detach().end().html;
      this.$el.html(this.template(this.model.attributes));
      if (!this.model.get('revealed')) {
        return this.$el.children().children()[0].className = 'card back covered';
      }
    };

    return CardView;

  })(Backbone.View);

}).call(this);

/*
//@ sourceMappingURL=CardView.map
*/
