// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Stack = (function(_super) {
    __extends(Stack, _super);

    function Stack() {
      _ref = Stack.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Stack.prototype.initialize = function() {
      this.set('chipStack', 2000);
      this.set('curBet', 0);
      return this.set('betSet', false);
    };

    return Stack;

  })(Backbone.Model);

}).call(this);

/*
//@ sourceMappingURL=Stack.map
*/
